
export const languageData = {
    en:{
      Login:"Login",
      signup:"Sign Up",
      personalinfo:"Personal Information",
      physicalinfo:"Physical Characteristics",
      personalpre:"Personal Preferences",
      personalinfodesc:"Hey there! We'd love to get to know you better to personalize your experience.",
      nameplaceholder:"Tell us your name",
      countryplaceholder:"Country",
      regionplaceholder:"City",
      selectage:" Select your age group",
      under16:"Under 16",
      1620:" 16-20 years old",
      2125:"21-25 years old",
      2635:"26-35 years old",
      3645:"36-45 years old",
      46:"Over 46 years old",
      AreYou:"Are You?",
      male:"Male",
      female:"Female",
      heightplaceholder:"Height in cm",
      weightplaceholder:"Weight in Kgs",
      Bodyshape:"Body Shape",
      next:"Next",
      LoginHead:" Welcome Back....!",
      Logindesc:"Great to see you again! Please enter your phone number to continue.",
      Loginpaagebutton:"Login",
      Skin:"Skin",
      prefrencedesc:"Hey there! We'd love to get to know you better to personalize your experience.",
      prefrence1desc:"Select your Style Aesthetics",
      favouritepattern:"Select your Favorite Pattern",
      favouritecolor:"Select your Favorite Colors",
      selectmore:"you can select more than one",
      topwear:"Select your Favorite Topwear",
      bottomwear:"Select your Favorite Bottomwear",
      footwear:"Select your Favorite Footwear",
    },
    ar:{
      Login:"تسجيل الدخول",
      signup:"إنشاء حساب",
      personalinfo:"المعلومات الشخصية",
      physicalinfo:"الخصائص الجسدية",
      personalpre:"التفضيلات",
      personalinfodesc:"هلا بالزين! حابين نتعرف عليك عشان نقدملك أفضل تجربة",
      nameplaceholder:"خبرنا باسمك",
      countryplaceholder:"الدولة",
      regionplaceholder:"المدينة",
      selectage:"حدد فئتك العمرية",
      under16:"أقل من 16 عام",
      1620:"من 16 - 20 عام",
      2125:"من 21 - 25 عام",
      2635:"من 26 -35 عام",
      3645:"من 36 - 45 عام",
      46:"فوق 46 عام",
      AreYou:"هل أنت؟",
      male:"ذكر",
      female:"أنثى",
      heightplaceholder:"طولك",
      weightplaceholder:"وزنك",
      Bodyshape:"شكل الجسم",
      next:"التالي",
      LoginHead:"يا مرحبا!",
      Logindesc:"يازين من جانا! زودنا برقم جوالك للاستمرار.",
      Loginpaagebutton:"تسجيل الدخول",
      Skin:"",
      prefrencedesc:"هلا بالزين! حابين نتعرف عليك عشان نقدملك أفضل تجربة",
      prefrence1desc:"اختاري ستايلات الملابس المفضلة لك",
      favouritepattern:"حددي النقوش المناسبة لك",
      favouritecolor:"حددي الألوان المفضلة لك",
      selectmore:"يُمكنك اختيار أكثر من خيار واحد",
      topwear:"حددي اللباس العلوي المفضل لك",
      bottomwear:"حددي اللباس السفلي المفضل لك",
      footwear:"حددي الأحذية المفضلة لك",
    }
}